### ISSUE TITLE
How could i change the background to white for example?

### ISSUE THREAD

**Issue by funkeeflow** [PavelDoGreat/WebGL-Fluid-Simulation#3]

**Comment by MaxBittker** [comment]
try changing displayShader

**Comment by mozgbrasil** [comment]
Hello good afternoon

I did not make it

Can you demonstrate what I would have to do based on your script

https://github.com/PavelDoGreat/WebGL-Fluid-Simulation/blob/master/script.js

Is it possible to leave the background transparent?

**Comment by PavelDoGreat** [comment]
@mozgbrasil okay man, I can't check now if it works, but here is some suggestions:

[In line 24](https://github.com/PavelDoGreat/WebGL-Fluid-Simulation/blob/50228a22136555d108245eae5f0050f57e376d16/script.js#L24) change alpha parameter to true.

Change displayShader to this:
 ```
void main () {
    vec3 c = texture2D(uTexture, vUv).rgb;
    float a= (c.r + c.g + c.b) / 3.0;
    gl_FragColor = vec4(c, a);
}
```

Also insert before [line 635](https://github.com/PavelDoGreat/WebGL-Fluid-Simulation/blob/50228a22136555d108245eae5f0050f57e376d16/script.js#L635) this code:
`gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);`

If it wouldn't work, just google about webgl blending, because I myself don't know much about it

**Comment by MaxBittker** [comment]
you also might want to read the book of shaders for some background knowledge 
https://thebookofshaders.com
it's a GREAT free resource

**Comment by mozgbrasil** [comment]
Hello good afternoon

It worked

Thank you my friends

**Comment by MaxBittker** [comment]
wohooo!
